In [1]:
import numpy as np
import pandas as pd
import scipy.stats as stats
import statsmodels.api 

import warnings 
warnings.filterwarnings('ignore')

import seaborn as sns
import matplotlib.pyplot as plt

## Q-1

In [207]:
loans = pd.read_csv(r'LoansData.csv')
loans

Amount_Requested  Amount_Funded_By_Investors Interest_Rate Loan_Length  \
0              20000.0                    20000.00         8.90%   36 months   
1              19200.0                    19200.00        12.12%   36 months   
2              35000.0                    35000.00        21.98%   60 months   
3              10000.0                     9975.00         9.99%   36 months   
4              12000.0                    12000.00        11.71%   36 months   
...                ...                         ...           ...         ...   
2495           30000.0                    29950.00        16.77%   60 months   
2496           16000.0                    16000.00        14.09%   60 months   
2497           10000.0                    10000.00        13.99%   36 months   
2498            6000.0                     6000.00        12.42%   36 months   
2499            9000.0                     5242.75        13.79%   36 months   

            Loan_Purpose Debt_To_Income_Ratio State Home_Ownership  \
0     debt_consolidation               14.90%    SC       MORTGAGE   
1     debt_consolidation               28.36%    TX       MORTGAGE   
2     debt_consolidation               23.81%    CA       MORTGAGE   
3     debt_consolidation               14.30%    KS       MORTGAGE   
4            credit_card               18.78%    NJ           RENT   
...                  ...                  ...   ...            ...   
2495  debt_consolidation               19.23%    NY       MORTGAGE   
2496    home_improvement               21.54%    MD            OWN   
2497  debt_consolidation                4.89%    PA       MORTGAGE   
2498      major_purchase               16.66%    NJ           RENT   
2499  debt_consolidation                6.76%    NY           RENT   

      Monthly_Income FICO_Range  Open_CREDIT_Lines  Revolving_CREDIT_Balance  \
0            6541.67    735-739               14.0                   14272.0   
1            4583.33    715-719               12.0                   11140.0   
2           11500.00    690-694               14.0                   21977.0   
3            3833.33    695-699               10.0                    9346.0   
4            3195.00    695-699               11.0                   14469.0   
...              ...        ...                ...                       ...   
2495         9250.00    705-709               15.0                   45880.0   
2496         8903.25    740-744               18.0                   18898.0   
2497         2166.67    680-684                4.0                    4544.0   
2498         3500.00    675-679                8.0                    7753.0   
2499         3875.00    670-674                7.0                    7589.0   

      Inquiries_in_the_Last_6_Months Employment_Length  
0                                2.0          < 1 year  
1                                1.0           2 years  
2                                1.0           2 years  
3                                0.0           5 years  
4                                0.0           9 years  
...                              ...               ...  
2495                             1.0           8 years  
2496                             1.0         10+ years  
2497                             0.0         10+ years  
2498                             0.0           5 years  
2499                             0.0         10+ years  

[2500 rows x 14 columns]

In [208]:
loans = loans.dropna()

In [209]:
loans.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 2413 entries, 0 to 2499
Data columns (total 14 columns):
 #   Column                          Non-Null Count  Dtype  
---  ------                          --------------  -----  
 0   Amount_Requested                2413 non-null   float64
 1   Amount_Funded_By_Investors      2413 non-null   float64
 2   Interest_Rate                   2413 non-null   object 
 3   Loan_Length                     2413 non-null   object 
 4   Loan_Purpose                    2413 non-null   object 
 5   Debt_To_Income_Ratio            2413 non-null   object 
 6   State                           2413 non-null   object 
 7   Home_Ownership                  2413 non-null   object 
 8   Monthly_Income                  2413 non-null   float64
 9   FICO_Range                      2413 non-null   object 
 10  Open_CREDIT_Lines               2413 non-null   float64
 11  Revolving_CREDIT_Balance        2413 non-null   float64
 12  Inquiries_in_the_Last_6_Months  24

In [210]:
loans['Interest_Rate'] = loans['Interest_Rate'].str.slice(0,-1)
loans['Interest_Rate'] = pd.to_numeric(loans.Interest_Rate)

In [211]:
loans['Loan_Length'] = loans['Loan_Length'].str.slice(0,2)
loans['Loan_Length'] = pd.to_numeric(loans['Loan_Length'])

In [212]:
a = loans["Amount_Funded_By_Investors"]
b = loans["Interest_Rate"]

In [213]:
stats.ttest_ind(loans.Amount_Funded_By_Investors,loans.Interest_Rate)

Ttest_indResult(statistic=76.66587325965071, pvalue=0.0)

In [214]:
# pvalue=0 < 0.05, At 95% Confidence level we reject null hypothesis H0

# Therefore, Interest rate is varied for different loan amounts

In [215]:
x = loans['Loan_Length']
y = loans["Interest_Rate"]

In [216]:
stats.ttest_ind(x,y)

Ttest_indResult(statistic=128.36728199919077, pvalue=0.0)

In [217]:
# pvalue=0 < 0.05, At 95% Confidence level we reject null hypothesis H0

# Therefore, Loan length is directly affecting interest rate

In [219]:
loans.Loan_Purpose.nunique()

14

In [220]:
loans.groupby('Loan_Purpose').nunique()

Amount_Requested  Amount_Funded_By_Investors  \
Loan_Purpose                                                       
car                               30                          42   
credit_card                      149                         210   
debt_consolidation               280                         460   
educational                       11                          13   
home_improvement                  74                         105   
house                             16                          16   
major_purchase                    45                          62   
medical                           22                          24   
moving                            15                          22   
other                             77                         110   
renewable_energy                   4                           4   
small_business                    46                          66   
vacation                          15                          16   
wedding                           22                          27   

                    Interest_Rate  Loan_Length  Debt_To_Income_Ratio  State  \
Loan_Purpose                                                                  
car                            36            2                    50     20   
credit_card                   130            2                   392     43   
debt_consolidation            217            2                  1006     44   
educational                    14            2                    14      8   
home_improvement               84            2                   144     34   
house                          19            2                    20     12   
major_purchase                 62            2                    99     26   
medical                        25            2                    28     19   
moving                         27            2                    29     15   
other                         100            2                   179     33   
renewable_energy                4            1                     4      3   
small_business                 63            2                    83     24   
vacation                       20            2                    19      9   
wedding                        29            2                    37     16   

                    Home_Ownership  Monthly_Income  FICO_Range  \
Loan_Purpose                                                     
car                              3              41          23   
credit_card                      4             166          32   
debt_consolidation               4             395          35   
educational                      3              13          11   
home_improvement                 3              92          32   
house                            3              19          15   
major_purchase                   3              77          29   
medical                          4              26          19   
moving                           3              27          15   
other                            3             132          31   
renewable_energy                 2               4           4   
small_business                   3              55          28   
vacation                         3              16          12   
wedding                          3              31          20   

                    Open_CREDIT_Lines  Revolving_CREDIT_Balance  \
Loan_Purpose                                                      
car                                16                        49   
credit_card                        24                       426   
debt_consolidation                 28                      1232   
educational                        10                        14   
home_improvement                   21                       144   
house                              10                        20   
major_purchase                     17                        96   
medica

In [221]:
g1 = loans.loc[loans['Loan_Purpose']=='car']['Interest_Rate']
g2 = loans.loc[loans['Loan_Purpose']=='credit_card']['Interest_Rate']
g3 = loans.loc[loans['Loan_Purpose']=='debt_consolidation']['Interest_Rate']
g4 = loans.loc[loans['Loan_Purpose']=='educational']['Interest_Rate']
g5 = loans.loc[loans['Loan_Purpose']=='home_improvement']['Interest_Rate']
g6 = loans.loc[loans['Loan_Purpose']=='house']['Interest_Rate']
g7 = loans.loc[loans['Loan_Purpose']=='major_purchase']['Interest_Rate']
g8 = loans.loc[loans['Loan_Purpose']=='medical']['Interest_Rate']
g9 = loans.loc[loans['Loan_Purpose']=='moving']['Interest_Rate']
g10 = loans.loc[loans['Loan_Purpose']=='other']['Interest_Rate']
g11 = loans.loc[loans['Loan_Purpose']=='renewable_energy']['Interest_Rate']
g12 = loans.loc[loans['Loan_Purpose']=='small_business']['Interest_Rate']
g13 = loans.loc[loans['Loan_Purpose']=='vacation']['Interest_Rate']
g14 = loans.loc[loans['Loan_Purpose']=='wedding']['Interest_Rate']


In [222]:
stats.f_oneway(g1,g2,g3,g4,g5,g6,g7,g8,g9,g10,g11,g12,g13,g14)

F_onewayResult(statistic=7.330838185919651, pvalue=2.7646672581411367e-14)

In [ ]:
# pvalue=2.76 > 0.05, At 95% confidene level we reject null hypothesis

# Therefore, Interest rate varies for different purpose of loans

In [223]:
loans.dtypes

Amount_Requested                  float64
Amount_Funded_By_Investors        float64
Interest_Rate                     float64
Loan_Length                         int64
Loan_Purpose                       object
Debt_To_Income_Ratio               object
State                              object
Home_Ownership                     object
Monthly_Income                    float64
FICO_Range                         object
Open_CREDIT_Lines                 float64
Revolving_CREDIT_Balance          float64
Inquiries_in_the_Last_6_Months    float64
Employment_Length                  object
dtype: object

In [226]:
# using Crosstabs
CrossTable = pd.crosstab(loans['FICO_Range'],loans['Home_Ownership'],margins=True)
CrossTable

Home_Ownership  MORTGAGE  OTHER  OWN  RENT   All
FICO_Range                                      
640-644                0      0    1     4     5
645-649                1      0    0     2     3
650-654                1      0    0     0     1
655-659                0      1    0     3     4
660-664               40      0   14    64   118
665-669               52      0   17    69   138
670-674               66      1   13    87   167
675-679               78      1   10    72   161
680-684               55      2    9    91   157
685-689               58      0   10    60   128
690-694               52      0    9    74   135
695-699               64      0   10    72   146
700-704               57      0   10    57   124
705-709               65      0   12    54   131
710-714               52      0   10    45   107
715-719               45      0    2    45    92
720-724               46      0    0    62   108
725-729               45      0    5    41    91
730-734               46      0    7    41    94
735-739               30      0    6    29    65
740-744               24      0    4    22    50
745-749               26      0    7    21    54
750-754               32      0    4    24    60
755-759               27      0    5    12    44
760-764               27      0    4    14    45
765-769               18      0    3    11    32
770-774               12      0    1     4    17
775-779               13      0    3     6    22
780-784               19      0    3     4    26
785-789               12      0    1     4    17
790-794               15      0    1     4    20
795-799                7      0    1     5    13
800-804                7      0    3     2    12
805-809                6      0    2     3    11
810-814                5      0    1     2     8
815-819                5      0    0     0     5
820-824                0      0    1     0     1
830-834                1      0    0     0     1
All                 1109      5  189  1110  2413

In [227]:
stats.chi2_contingency(CrossTable)

(269.7881202757334,
 1.3041014985761142e-08,
 152,
 array([[2.29796933e+00, 1.03605470e-02, 3.91628678e-01, 2.30004144e+00,
         5.00000000e+00],
        [1.37878160e+00, 6.21632822e-03, 2.34977207e-01, 1.38002487e+00,
         3.00000000e+00],
        [4.59593867e-01, 2.07210941e-03, 7.83257356e-02, 4.60008288e-01,
         1.00000000e+00],
        [1.83837547e+00, 8.28843763e-03, 3.13302942e-01, 1.84003315e+00,
         4.00000000e+00],
        [5.42320763e+01, 2.44508910e-01, 9.24243680e+00, 5.42809780e+01,
         1.18000000e+02],
        [6.34239536e+01, 2.85951098e-01, 1.08089515e+01, 6.34811438e+01,
         1.38000000e+02],
        [7.67521757e+01, 3.46042271e-01, 1.30803978e+01, 7.68213842e+01,
         1.67000000e+02],
        [7.39946125e+01, 3.33609615e-01, 1.26104434e+01, 7.40613344e+01,
         1.61000000e+02],
        [7.21562370e+01, 3.25321177e-01, 1.22971405e+01, 7.22213013e+01,
         1.57000000e+02],
        [5.88280149e+01, 2.65230004e-01, 1.00256942e+01, 5

## Q-2

In [2]:
price = pd.read_csv('Price_Quotes.csv')

In [3]:
price

Order_Number  Barry_Price  Mary_Price
0              1          126         114
1              2          110         118
2              3          138         114
3              4          142         111
4              5          146         129
5              6          136         119
6              7           94          97
7              8          103         104
8              9          140         127
9             10          152         133
10            11          108         103
11            12           97         108

In [4]:
price.Barry_Price.mean()

124.33333333333333

In [5]:
price.Mary_Price.mean()

114.75

In [6]:
price.Barry_Price.std()

20.698411591816473

In [7]:
price.Mary_Price.std()

11.054616477044577

In [8]:
len(price)

12

In [9]:
SE_Barry = price.Barry_Price.std() / np.sqrt(len(price))
SE_Barry

5.975116752166456

In [10]:
SE_Mary = price.Mary_Price.std() / np.sqrt(len(price))
SE_Mary

3.19119289940488

In [11]:
# Paired t test
stats.ttest_ind(price.Mary_Price,price.Barry_Price)

Ttest_indResult(statistic=-1.4147436739281787, pvalue=0.17114226132118285)

In [48]:
#  The significance pvalue=0.1711422 > 0.05 at 95% of confidence level
#  We do not reject H0
# The avg price quotes provided by Mary and Barry is same
# There is no difference in their price quotes

## Q-3

In [12]:
treatment = pd.read_csv('Treatment_Facility.csv')
treatment

Month Reengineer  Employee_Turnover       VAR4        VAR5
0       1      Prior             0.0000  24.390244   42.682927
1       2      Prior             6.0606  19.354839   25.806452
2       3      Prior            12.1212  35.087719  146.198830
3       4      Prior             3.3333  18.404908  110.429448
4       5      Prior            12.9032  17.964072   23.952096
5       6      Prior             9.6774  41.176471   47.058824
6       7      Prior            11.7647  13.422819    0.000000
7       8      Prior            11.4286  31.250000   25.000000
8       9      Prior            23.0769  17.241379  132.183908
9      10      Prior            15.0000  16.574586   16.574586
10     11      Prior            10.0000   5.917160   88.757396
11     12      Prior            26.0870  21.164021   31.746032
12     13      Prior            11.1111   5.076142   10.152284
13     14       Post            26.6667   9.708738   29.126214
14     15       Post            17.9487   4.201681   21.008403
15     16       Post            12.8205  13.043478   34.782609
16     17       Post            15.7895   9.950249   19.900498
17     18       Post             0.0000   9.950249    9.950249
18     19       Post            30.7692   8.510638   25.531915
19     20       Post            26.8293   9.259259   23.148148

In [13]:
g1 = treatment.Employee_Turnover[treatment.Reengineer=='Prior']
g1

0      0.0000
1      6.0606
2     12.1212
3      3.3333
4     12.9032
5      9.6774
6     11.7647
7     11.4286
8     23.0769
9     15.0000
10    10.0000
11    26.0870
12    11.1111
Name: Employee_Turnover, dtype: float64

In [14]:
g2 = treatment.Employee_Turnover[treatment.Reengineer=='Post']
g2

13    26.6667
14    17.9487
15    12.8205
16    15.7895
17     0.0000
18    30.7692
19    26.8293
Name: Employee_Turnover, dtype: float64

In [15]:
g1.mean()

11.735692307692307

In [16]:
g2.mean()

18.68912857142857

In [19]:
# comparing 2 independent samples using ttest_ind
stats.ttest_ind(g1,g2)


Ttest_indResult(statistic=-1.770306704753604, pvalue=0.09361109345535304)

In [21]:
#stats.f_oneway(g1,g2)

F_onewayResult(statistic=3.133985828895568, pvalue=0.09361109345535291)

In [62]:
# The significance pvalue=0.0936 >  0.05 at 95% of confidence level

# We can't reject null hypothesis 

# Business:- The reengineering effort did not change the critical incidence rate
# Therefore, we can say that the Critical Incidence rate is not improved.

## Q-4

In [22]:
priority = pd.read_csv('Priority_Assessment.csv')
priority

Days Priority
0     3.3     High
1     7.9   Medium
2     0.3     High
3     0.7   Medium
4     8.6   Medium
..    ...      ...
637   2.5      Low
638   0.3     High
639   0.3   Medium
640   1.3   Medium
641   0.5     High

[642 rows x 2 columns]

In [23]:
high_g1 = priority.Days[priority.Priority == 'High']
high_g1

0      3.3
2      0.3
5      0.3
6      0.3
7      0.3
      ... 
631    0.3
632    1.0
635    0.1
638    0.3
641    0.5
Name: Days, Length: 326, dtype: float64

In [24]:
medium_g2 = priority.Days[priority.Priority == 'Medium']
medium_g2

1       7.9
3       0.7
4       8.6
9      15.9
11      0.3
       ... 
633     2.0
634     2.5
636     0.1
639     0.3
640     1.3
Name: Days, Length: 249, dtype: float64

In [25]:
low_g3 = priority.Days[priority.Priority == 'Low']
low_g3

14     23.2
15      5.3
20      4.6
23      1.8
26     17.0
       ... 
609     0.5
613     7.9
620     0.3
622     0.1
637     2.5
Name: Days, Length: 67, dtype: float64

In [26]:
#mean of high, medium and low at sample level
high_g1.mean()

3.023619631901845

In [27]:
medium_g2.mean()

2.5000000000000004

In [28]:
low_g3.mean()

4.228358208955225

In [29]:
## Comparing more than two samples or groups so using f-test
stats.f_oneway(high_g1,medium_g2,low_g3)

F_onewayResult(statistic=1.812311010076072, pvalue=0.16411459461716182)

In [80]:
# pvalue=0.164 > 0.05 with 95% of confidence level

# We donot reject null hypothesis

# Business:- All prioritization working system jobs is same.
# Therefore, speed of system for completing of high,medium or low priority jobs is same
# Thus overall project completion time is not lowered , it is same.

## Q-5

In [72]:
films = pd.read_csv(r'Films.csv')
films = films.drop(columns='_rowstate_')
films

Movie  Gender Marital_Status  Sinage  Parking  Clean  \
0    Ferris Buellers Day Off  Female        Married     2.0      2.0    2.0   
1    Ferris Buellers Day Off  Female         Single     1.0      1.0    1.0   
2    Ferris Buellers Day Off    Male        Married     2.0      4.0    3.0   
3    Ferris Buellers Day Off  Female        Married     1.0      3.0    2.0   
4    Ferris Buellers Day Off  Female        Married     1.0      1.0    1.0   
..                       ...     ...            ...     ...      ...    ...   
325               Old School       2              2     1.0      2.0    1.0   
326               Old School       1              1     2.0      2.0    2.0   
327               Old School       2              1     2.0      1.0    1.0   
328               Old School       1              1     1.0      1.0    1.0   
329               Old School       2              2     2.0      2.0    3.0   

     Overall  Age  Income Hear_About  
0        2.0  3.0     1.0          5  
1        1.0  2.0     1.0          5  
2        2.0  4.0     1.0          5  
3        2.0  4.0     1.0          5  
4        1.0  3.0     3.0          1  
..       ...  ...     ...        ...  
325      1.0  2.0     1.0          1  
326      2.0  3.0     3.0          5  
327      2.0  2.0     2.0          5  
328      1.0  2.0     1.0          3  
329      1.0  2.0     1.0          5  

[330 rows x 10 columns]

In [73]:
films.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 330 entries, 0 to 329
Data columns (total 10 columns):
 #   Column          Non-Null Count  Dtype  
---  ------          --------------  -----  
 0   Movie           330 non-null    object 
 1   Gender          330 non-null    object 
 2   Marital_Status  328 non-null    object 
 3   Sinage          328 non-null    float64
 4   Parking         328 non-null    float64
 5   Clean           327 non-null    float64
 6   Overall         328 non-null    float64
 7   Age             328 non-null    float64
 8   Income          314 non-null    float64
 9   Hear_About      323 non-null    object 
dtypes: float64(6), object(4)
memory usage: 25.9+ KB


In [74]:
films = films.dropna()
films

Movie  Gender Marital_Status  Sinage  Parking  Clean  \
0    Ferris Buellers Day Off  Female        Married     2.0      2.0    2.0   
1    Ferris Buellers Day Off  Female         Single     1.0      1.0    1.0   
2    Ferris Buellers Day Off    Male        Married     2.0      4.0    3.0   
3    Ferris Buellers Day Off  Female        Married     1.0      3.0    2.0   
4    Ferris Buellers Day Off  Female        Married     1.0      1.0    1.0   
..                       ...     ...            ...     ...      ...    ...   
325               Old School       2              2     1.0      2.0    1.0   
326               Old School       1              1     2.0      2.0    2.0   
327               Old School       2              1     2.0      1.0    1.0   
328               Old School       1              1     1.0      1.0    1.0   
329               Old School       2              2     2.0      2.0    3.0   

     Overall  Age  Income Hear_About  
0        2.0  3.0     1.0          5  
1        1.0  2.0     1.0          5  
2        2.0  4.0     1.0          5  
3        2.0  4.0     1.0          5  
4        1.0  3.0     3.0          1  
..       ...  ...     ...        ...  
325      1.0  2.0     1.0          1  
326      2.0  3.0     3.0          5  
327      2.0  2.0     2.0          5  
328      1.0  2.0     1.0          3  
329      1.0  2.0     1.0          5  

[301 rows x 10 columns]

### 5. i. overall level of customer satisfaction level

In [6]:
mean = films.Overall.mean()
SD = films.Overall.std()
length = len(films)
print(mean, SD, length)

1.6212624584717608 0.6753367561589327 301


In [7]:
SE = SD / np.sqrt(length)
SE

0.038925763497347034

In [8]:
# 95% confidence intervals
L = mean - (1.96 * SE)
U = mean + (1.96 * SE)
print(L, U)

1.5449679620169605 1.697556954926561


 Overall customer satisfaction lies between (1.5445322728780404,1.69327260517074) at 95% confidence level.

### 5. ii. Factors linked to satisfaction


In [9]:
# Using chi square test to check the independence of variables at 95% confidence level.

# H0: No relationship, independent
# H1: There is relationship, dependent
obs = pd.crosstab(films.Sinage,films.Overall)

stats.chi2_contingency(obs)

# p=3.054444776360607e-18 < 0.05 , we reject Ho
# Overall satisfaction is dependent on Sinage
# when increase in sinage, Overall satisfaction also increases

(121.32462033201084,
 3.054444776360607e-18,
 16,
 array([[4.77906977e+01, 5.16279070e+01, 4.18604651e+00, 3.48837209e-01,
         1.04651163e+00],
        [6.37209302e+01, 6.88372093e+01, 5.58139535e+00, 4.65116279e-01,
         1.39534884e+00],
        [2.04817276e+01, 2.21262458e+01, 1.79401993e+00, 1.49501661e-01,
         4.48504983e-01],
        [2.73089701e+00, 2.95016611e+00, 2.39202658e-01, 1.99335548e-02,
         5.98006645e-02],
        [2.27574751e+00, 2.45847176e+00, 1.99335548e-01, 1.66112957e-02,
         4.98338870e-02]]))

In [10]:
# H0: No relationship, independent
# H1: There is relationship, dependent
obs = pd.crosstab(films.Parking,films.Overall)

stats.chi2_contingency(obs)

# p=1.2264032549812005e-37 < 0.05 , we reject Ho
# Overall satisfaction is dependent on Parking
# when increase in Parking efficiency, Overall satisfaction also increases.

(218.79348282085004,
 1.2264032549812005e-37,
 16,
 array([[5.55282392e+01, 5.99867110e+01, 4.86378738e+00, 4.05315615e-01,
         1.21594684e+00],
        [6.32657807e+01, 6.83455150e+01, 5.54152824e+00, 4.61794020e-01,
         1.38538206e+00],
        [1.31993355e+01, 1.42591362e+01, 1.15614618e+00, 9.63455150e-02,
         2.89036545e-01],
        [3.18604651e+00, 3.44186047e+00, 2.79069767e-01, 2.32558140e-02,
         6.97674419e-02],
        [1.82059801e+00, 1.96677741e+00, 1.59468439e-01, 1.32890365e-02,
         3.98671096e-02]]))

In [11]:
# H0: No relationship, independent
# H1: There is relationship, dependent
obs = pd.crosstab(films.Clean,films.Overall)

stats.chi2_contingency(obs)

# p=9.882317099745693e-20 < 0.05 , we reject Ho
# Overall satisfaction is dependent on Cleanliness
# When cleaniness of the venue increases,  Overall satisfaction also increases.

(129.0342392337068,
 9.882317099745693e-20,
 16,
 array([[6.09900332e+01, 6.58870432e+01, 5.34219269e+00, 4.45182724e-01,
         1.33554817e+00],
        [6.28106312e+01, 6.78538206e+01, 5.50166113e+00, 4.58471761e-01,
         1.37541528e+00],
        [1.00132890e+01, 1.08172757e+01, 8.77076412e-01, 7.30897010e-02,
         2.19269103e-01],
        [2.27574751e+00, 2.45847176e+00, 1.99335548e-01, 1.66112957e-02,
         4.98338870e-02],
        [9.10299003e-01, 9.83388704e-01, 7.97342193e-02, 6.64451827e-03,
         1.99335548e-02]]))

In [12]:
# H0: No relationship, independent
# H1: There is relationship, dependent
obs = pd.crosstab(films.Age,films.Overall)

stats.chi2_contingency(obs)

# p=0.5267913370930692 > 0.05 , Accept Ho
# Overall satisfaction Person's age doesn't depend on each other.

(11.024837235069565,
 0.5267913370930692,
 12,
 array([[1.00132890e+01, 1.08172757e+01, 8.77076412e-01, 7.30897010e-02,
         2.19269103e-01],
        [7.46445183e+01, 8.06378738e+01, 6.53820598e+00, 5.44850498e-01,
         1.63455150e+00],
        [4.91561462e+01, 5.31029900e+01, 4.30564784e+00, 3.58803987e-01,
         1.07641196e+00],
        [3.18604651e+00, 3.44186047e+00, 2.79069767e-01, 2.32558140e-02,
         6.97674419e-02]]))

In [13]:
# H0: No relationship, independent
# H1: There is relationship, dependent
obs = pd.crosstab(films.Income,films.Overall)

stats.chi2_contingency(obs)

# p=0.7631326888324932 > 0.05 , Accept Ho
# Overall satisfaction is not dependent on Income.

(4.9478735426424,
 0.7631326888324932,
 8,
 array([[61.44518272, 66.37873754,  5.3820598 ,  0.44850498,  1.34551495],
        [36.41196013, 39.33554817,  3.18936877,  0.26578073,  0.79734219],
        [39.14285714, 42.28571429,  3.42857143,  0.28571429,  0.85714286]]))

In [14]:
# H0: No relationship, independent
# H1: There is relationship, dependent
obs = pd.crosstab(films.Hear_About,films.Overall)

stats.chi2_contingency(obs)

# p=0.9920532791201511 > 0.05 ,Accept Ho
# Overall satisfaction is not dependent on Hear_about.

(21.659744148982803,
 0.9920532791201511,
 40,
 array([[8.64784053e+00, 9.34219269e+00, 7.57475083e-01, 6.31229236e-02,
         1.89368771e-01],
        [4.55149502e-01, 4.91694352e-01, 3.98671096e-02, 3.32225914e-03,
         9.96677741e-03],
        [5.00664452e+00, 5.40863787e+00, 4.38538206e-01, 3.65448505e-02,
         1.09634551e-01],
        [9.10299003e-01, 9.83388704e-01, 7.97342193e-02, 6.64451827e-03,
         1.99335548e-02],
        [5.91694352e+00, 6.39202658e+00, 5.18272425e-01, 4.31893688e-02,
         1.29568106e-01],
        [4.55149502e-01, 4.91694352e-01, 3.98671096e-02, 3.32225914e-03,
         9.96677741e-03],
        [4.55149502e-01, 4.91694352e-01, 3.98671096e-02, 3.32225914e-03,
         9.96677741e-03],
        [1.77508306e+01, 1.91760797e+01, 1.55481728e+00, 1.29568106e-01,
         3.88704319e-01],
        [4.55149502e-01, 4.91694352e-01, 3.98671096e-02, 3.32225914e-03,
         9.96677741e-03],
        [9.64916944e+01, 1.04239203e+02, 8.45182724e+00, 7.043

In [15]:
# H0: No relationship, independent
# H1: There is relationship, dependent
obs = pd.crosstab(films.Gender,films.Overall)

stats.chi2_contingency(obs)

# p=0.2876685403329753 > 0.05 ,Accept Ho 
# Overall satisfaction is not dependent on Hear_about.

(14.207273286990997,
 0.2876685403329753,
 12,
 array([[4.23289037e+01, 4.57275748e+01, 3.70764120e+00, 3.08970100e-01,
         9.26910299e-01],
        [8.14717608e+01, 8.80132890e+01, 7.13621262e+00, 5.94684385e-01,
         1.78405316e+00],
        [7.28239203e+00, 7.86710963e+00, 6.37873754e-01, 5.31561462e-02,
         1.59468439e-01],
        [5.91694352e+00, 6.39202658e+00, 5.18272425e-01, 4.31893688e-02,
         1.29568106e-01]]))

In [16]:
# H0: No relationship, independent
# H1: There is relationship, dependent
obs = pd.crosstab(films.Marital_Status,films.Overall)

stats.chi2_contingency(obs)

# p=0.8205155680018543 > 0.05 ,Accept Ho
# Overall satisfaction is not dependent on Martial status.

(10.819027209857504,
 0.8205155680018543,
 16,
 array([[3.64119601e+01, 3.93355482e+01, 3.18936877e+00, 2.65780731e-01,
         7.97342193e-01],
        [8.73887043e+01, 9.44053156e+01, 7.65448505e+00, 6.37873754e-01,
         1.91362126e+00],
        [5.00664452e+00, 5.40863787e+00, 4.38538206e-01, 3.65448505e-02,
         1.09634551e-01],
        [7.28239203e+00, 7.86710963e+00, 6.37873754e-01, 5.31561462e-02,
         1.59468439e-01],
        [9.10299003e-01, 9.83388704e-01, 7.97342193e-02, 6.64451827e-03,
         1.99335548e-02]]))

In [78]:
# Assigning Males as 1 and Females as 2 in gender column
films.Gender = np.where(films.Gender == '1','Male',films.Gender)
films.Gender = np.where(films.Gender == '2', 'Female',films.Gender)
films

Movie  Gender Marital_Status  Sinage  Parking  Clean  \
0    Ferris Buellers Day Off  Female        Married     2.0      2.0    2.0   
1    Ferris Buellers Day Off  Female         Single     1.0      1.0    1.0   
2    Ferris Buellers Day Off    Male        Married     2.0      4.0    3.0   
3    Ferris Buellers Day Off  Female        Married     1.0      3.0    2.0   
4    Ferris Buellers Day Off  Female        Married     1.0      1.0    1.0   
..                       ...     ...            ...     ...      ...    ...   
325               Old School  Female              2     1.0      2.0    1.0   
326               Old School    Male              1     2.0      2.0    2.0   
327               Old School  Female              1     2.0      1.0    1.0   
328               Old School    Male              1     1.0      1.0    1.0   
329               Old School  Female              2     2.0      2.0    3.0   

     Overall  Age  Income Hear_About  
0        2.0  3.0     1.0          5  
1        1.0  2.0     1.0          5  
2        2.0  4.0     1.0          5  
3        2.0  4.0     1.0          5  
4        1.0  3.0     3.0          1  
..       ...  ...     ...        ...  
325      1.0  2.0     1.0          1  
326      2.0  3.0     3.0          5  
327      2.0  2.0     2.0          5  
328      1.0  2.0     1.0          3  
329      1.0  2.0     1.0          5  

[301 rows x 10 columns]

### 5. iii. demographic profile of Film on the Rocks patrons

In [81]:
# Demography on Gender

gender = films.groupby('Gender')[['Gender']].count()
gender = gender.rename(columns={'Gender': 'count'}).reset_index() #renaming and resetting the index 
gender['Probability'] = gender['count'] / gender['count'].sum()
print(gender)
print(' \tThere is 64% prob that the patrons gender is Female ')

   Gender  count  Probability
0  Female    195     0.647841
1    Male    106     0.352159
 	There is 64% prob that the patrons gender is Female 


In [94]:
#Assigning 1 as single and 2 as married

films.Marital_Status = np.where(films.Marital_Status == '1','Single',films.Marital_Status)
films.Marital_Status = np.where(films.Marital_Status == '2','Married',films.Marital_Status)
films.Marital_Status = films.Marital_Status.replace('Slngle','Single')
films.Marital_Status.unique()

array(['Married', 'Single'], dtype=object)

In [98]:
# Demography on Marital_Status

Marital_Status = films.groupby('Marital_Status')[['Marital_Status']].count()
Marital_Status = Marital_Status.rename(columns={'Marital_Status': 'count'}).reset_index() #renaming and resetting the index 
Marital_Status['Probability'] =Marital_Status['count'] / Marital_Status['count'].sum()
print(Marital_Status)
print('\tThere is 67% probability that patrons marital status is married')
print('  \t 67% of the people who watched movies are married')

  Marital_Status  count  Probability
0        Married    203     0.674419
1         Single     98     0.325581
	There is 67% probability that patrons marital status is married
  	 67% of the people who watched movies are married


In [52]:
# Demography on Age

Age = films.groupby('Age')[['Age']].count()
Age = Age.rename(columns={'Age':'count'}).reset_index()
Age['Prob'] = Age['count'] /Age['count'].sum()
print(Age)
print('\nThere is 54% probability that patrons age is between 13-30 years.')

   Age  count      Prob
0  1.0     22  0.073090
1  2.0    164  0.544850
2  3.0    108  0.358804
3  4.0      7  0.023256

There is 54% probability that patrons age is between 13-30 years.


In [50]:
# Demography on Income

Income = films.groupby('Income')[['Income']].count()
Income = Income.rename(columns={'Income' : 'count'}).reset_index()
Income['Prob'] = Income['count'] / Income['count'].sum()
print(Income)
print('\nThere is 44% probabbility that patrons annual household income is less than $50,000.')

   Income  count      Prob
0     1.0    135  0.448505
1     2.0     80  0.265781
2     3.0     86  0.285714

There is 44% probabbility that patrons annual household income is less than $50,000.


### 5. iv. In what media outlet(s) should the film series be advertised

In [60]:


Hear_About = films.groupby('Hear_About')[['Hear_About']].count()
Hear_About = Hear_About.rename(columns={'Hear_About' : 'count'}).reset_index()
Hear_About['Prob'] = Hear_About['count'] / Hear_About['count'].sum()
print(Hear_About)
print('\nThere is 70% probability that people have heard about this film on Rocks by 5 word of mouth.')

   Hear_About  count      Prob
0           1     19  0.063123
1         1,5      1  0.003322
2           2     11  0.036545
3         2,5      2  0.006645
4           3     13  0.043189
5         3,4      1  0.003322
6         3,5      1  0.003322
7           4     39  0.129568
8         4,5      1  0.003322
9           5    212  0.704319
10        5,4      1  0.003322

There is 70% probability that people have heard about this film on Rocks by 5 word of mouth.
